# Generated by Django 5.2.6 on 2025-11-02 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Judul Kegiatan"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Kegiatan")),
                ("event_date", models.DateField(verbose_name="Tanggal Kegiatan")),
                ("event_time", models.TimeField(verbose_name="Waktu Kegiatan")),
                ("location", models.CharField(max_length=255, verbose_name="Lokasi")),
                (
                    "flyer",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="flyers/",
                        verbose_name="Flyer Kegiatan",
                    ),
                ),
                (
                    "certificate_template",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificate_templates/",
                        verbose_name="Template Sertifikat",
                    ),
                ),
                ("registration_closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
            },
        ),
    ]
