# Generated by Django 5.2.6 on 2025-11-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam atau Konten Menyesatkan"),
                            ("inappropriate", "Konten Tidak Pantas"),
                            ("fraud", "Penipuan atau Scam"),
                            ("duplicate", "Event Duplikat"),
                            ("other", "Lainnya"),
                        ],
                        max_length=50,
                        verbose_name="Alasan Laporan",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Laporan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Review"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="Feedback Admin"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="events.event",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Event",
                "verbose_name_plural": "Report Events",
                "db_table": "report_events",
                "unique_together": {("event", "reporter")},
            },
        ),
    ]
