# Generated by Django 5.2.6 on 2025-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_reportevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("seminar", "Seminar & Conference"),
                    ("concert", "Concert & Festival"),
                ],
                default="seminar",
                max_length=20,
                verbose_name="Kategori Event",
            ),
        ),
    ]
