# Generated by Django 5.2.6 on 2025-11-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Judul Berita"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar & Conference"),
                            ("concert", "Concert & Festival"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                ("content", models.TextField(verbose_name="Konten Berita")),
                (
                    "payment_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informasi Pembayaran"
                    ),
                ),
                (
                    "payment_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Batas Waktu Pembayaran"
                    ),
                ),
                (
                    "seminar_materials",
                    models.TextField(
                        blank=True, null=True, verbose_name="Materi Seminar"
                    ),
                ),
                (
                    "concert_lineup",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lineup Konser"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Gambar Utama",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Dipublikasikan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penulis",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="events.event",
                        verbose_name="Event Terkait",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "db_table": "news",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Komentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="events.news",
                        verbose_name="Berita",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Comment",
                "verbose_name_plural": "News Comments",
                "db_table": "news_comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
