# Generated by Django 5.2.6 on 2025-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_news_newscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bank_account",
            field=models.CharField(
                blank=True,
                help_text="Nomor rekening untuk pembayaran (jika event berbayar)",
                max_length=255,
                null=True,
                verbose_name="Nomor Rekening",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Nama bank (contoh: BCA, Mandiri, BRI)",
                max_length=100,
                null=True,
                verbose_name="Nama Bank",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kosongkan jika event gratis",
                max_digits=10,
                null=True,
                verbose_name="Harga Tiket",
            ),
        ),
    ]
