# Generated by Django 5.2.6 on 2025-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_bank_account_event_bank_name_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("offline", "Offline"),
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                ],
                default="offline",
                max_length=20,
                verbose_name="Tipe Lokasi",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom_link",
            field=models.URLField(
                blank=True,
                help_text="Link Zoom Meeting (jika event online/hybrid)",
                max_length=500,
                null=True,
                verbose_name="Link Zoom Meeting",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom_meeting_id",
            field=models.CharField(
                blank=True,
                help_text="Zoom Meeting ID (opsional)",
                max_length=50,
                null=True,
                verbose_name="Meeting ID",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom_passcode",
            field=models.CharField(
                blank=True,
                help_text="Zoom Passcode (opsional)",
                max_length=50,
                null=True,
                verbose_name="Passcode",
            ),
        ),
    ]
