# Generated by Django 5.2.6 on 2025-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_location_type_event_zoom_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="material_file",
            field=models.FileField(
                blank=True,
                help_text="Upload materi seminar (PDF, PPT, DOCX, ZIP). Hanya untuk event kategori Seminar.",
                null=True,
                upload_to="event_materials/",
                verbose_name="Materi Seminar",
            ),
        ),
    ]
