# Generated by Django 5.2.6 on 2025-11-02 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nama Lengkap")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format nomor telepon tidak valid",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="No. Handphone",
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat Tempat Tinggal")),
                (
                    "education",
                    models.CharField(
                        max_length=100, verbose_name="Pendidikan Terakhir"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("event_organizer", "Event Organizer"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_verification_expired",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_expired", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_password_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reset_password_expired", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expired_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "sessions",
            },
        ),
    ]
