# Generated by Django 5.2.6 on 2025-11-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="Suspended"),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Alasan Suspension"
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("report_valid", "Report Valid"),
                            ("community_guardian", "Community Guardian"),
                            ("truth_seeker", "Truth Seeker"),
                        ],
                        max_length=50,
                        verbose_name="Jenis Achievement",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Judul Achievement"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "icon",
                    models.CharField(
                        default="bi-trophy", max_length=50, verbose_name="Icon"
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievements",
                "ordering": ["-earned_at"],
            },
        ),
    ]
