# Generated by Django 5.2.6 on 2025-11-11 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_suspended_user_suspended_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organizer_name",
                    models.CharField(
                        help_text="Nama resmi organisasi atau perusahaan",
                        max_length=150,
                        verbose_name="Nama Organizer",
                    ),
                ),
                (
                    "person_in_charge",
                    models.CharField(
                        help_text="Nama lengkap penanggung jawab",
                        max_length=100,
                        verbose_name="Penanggung Jawab",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format nomor telepon tidak valid",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="No. Telepon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email resmi organizer (bisa berbeda dari email user)",
                        max_length=254,
                        verbose_name="Email Organizer",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Alamat lengkap kantor/organisasi",
                        verbose_name="Alamat Organizer",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Deskripsi singkat tentang organizer dan kegiatan yang biasa dilakukan",
                        verbose_name="Deskripsi Organizer",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Website organizer (opsional)",
                        null=True,
                        verbose_name="Website",
                    ),
                ),
                (
                    "social_media",
                    models.CharField(
                        blank=True,
                        help_text="Link social media (Instagram, Facebook, dll) - opsional",
                        max_length=255,
                        null=True,
                        verbose_name="Social Media",
                    ),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        help_text="Upload surat izin usaha atau dokumen legal lainnya (opsional)",
                        null=True,
                        upload_to="eo_docs/",
                        verbose_name="Surat Izin Usaha",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo organizer (opsional)",
                        null=True,
                        upload_to="eo_logos/",
                        verbose_name="Logo Organizer",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Status verifikasi oleh admin",
                        verbose_name="Terverifikasi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_organizer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Organizer",
                "verbose_name_plural": "Event Organizers",
                "db_table": "event_organizers",
                "ordering": ["-created_at"],
            },
        ),
    ]
