# Generated by Django 5.2.6 on 2025-11-08 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="payment_proofs/",
                verbose_name="Bukti Pembayaran",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Alasan Penolakan Pembayaran"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Tidak Diperlukan"),
                    ("pending", "Menunggu Validasi"),
                    ("approved", "Disetujui"),
                    ("rejected", "Ditolak"),
                ],
                default="not_required",
                max_length=20,
                verbose_name="Status Pembayaran",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tanggal Validasi Pembayaran"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="payment_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Divalidasi Oleh",
            ),
        ),
    ]
