# Generated by Django 5.2.6 on 2025-11-12 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_material_file"),
        ("registrations", "0002_eventregistration_payment_proof_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rejection_reason", models.TextField(verbose_name="Alasan Penolakan")),
                (
                    "rejected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Penolakan"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_rejections",
                        to="events.event",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ditolak Oleh",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Rejection",
                "verbose_name_plural": "Payment Rejections",
                "db_table": "payment_rejections",
                "ordering": ["-rejected_at"],
            },
        ),
    ]
